name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      run: sudo apt -y install googletest && dpkg -L googletest
    - name: link include
      run: sudo mkdir /usr/local/include/gtest && sudo ln -s /usr/src/googletest/googletest/include/gtest/gtest.h /usr/local/include/gtest/
    - uses: actions/checkout@v2
    - name: Make Vector
      run: cd vector && make test
    - name: Run
      run: ./vectorTest
   

# && make cp *.a /usr/lib