name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev cmake && cd /usr/src/gtest && cmake CMakeLists.txt 
    - uses: actions/checkout@v2
    - name: Make Vector
      run: cd vector && make test && ./vectorTest
   

# && make cp *.a /usr/lib