name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      run: wget https://github.com/google/googletest/archive/release-1.8.0.zip && unzip release-1.8.0.zip && ls && pwd
    - name: compile gtest
      run: ls && cd googletest-release-1.8.0/googletest && cmake . && make && ls
    - name: install lib gtest
      run: cd googletest-release-1.8.0/googletest  && sudo cp libgtest.a /usr/local/lib/
    - name: install lib gtest_main
      run: cd googletest-release-1.8.0/googletest  && sudo cp libgtest_main.a /usr/local/lib/
    - name: install gtest include
      run: cd googletest-release-1.8.0/googletest/include && sudo cp -r gtest /usr/local/include/
    - name: Check gtest
      run: ls /usr/local/lib/ && ls /usr/local/include/gtest/
    - uses: actions/checkout@v2
    - name: dry run make vector
      run: cd vector && make test -n
    - name: Make Vector
      run: cd vector && make test
    - name: Run
      run: ./vectorTest
